# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

target 'testMap' do
  pod 'GoogleMaps', '9.3.0'
  pod ‘GooglePlaces’
end
